CREATE USER app1user WITH ENCRYPTED PASSWORD 'password123';


CREATE DATABASE app1db WITH OWNER app1user;


GRANT ALL PRIVILEGES ON DATABASE app1db TO app1user;

GRANT ALL PRIVILEGES ON DATABASE postgres TO app1user;