version: "3.91"
services:

  fast_api:
    build:
      context: ./
      dockerfile: ./app/Dockerfile      
    image: local_image/fast_api       
    environment:
      - TZ=${timezone}
      - app_logs=/app/logs   
      - log_level=${log_level}     
      - app_name=${app_name}                  
    volumes: 
      - app_code_source:/app/app
      - logs-store:/app/logs 
      - common_libs:/app/common_libs
    command: >
        bash -c "/app/start.sh"         
    ports:
      - "${app_ports}"

  worker:
    build:
      context: ./worker/ 
      dockerfile: Dockerfile    
    image: local_image/worker 
    environment:       
      - TZ=${timezone}                              
    volumes: 
      - worker_code_source:/worker/worker
      - common_libs:/worker/common_libs   
    command: bash -c "/worker/start.sh"    
    #command: python src/worker.py         


  redis:
    hostname: redis    
    image: redis:8.6.1-alpine
    ports:
      - ${redis_port}  
    volumes:
      - type: bind
        source: ${redis_data_folder}
        target: /data   



volumes:

  app_code_source: 
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${app_code_source} 
  logs-store: 
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${logs_dir} 

  common_libs: 
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${common_libs} 

  worker_code_source: 
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${worker_code_source} 

      

