version: "3.91"
services:




  fast_api:
    build:
      context: ./
      dockerfile: ./app/Dockerfile      
    image: local_image/fast_api       
    environment:
      - TZ=${timezone}
      - app_logs=/app/logs   
      - log_level=${log_level}   
      - redis_url=${redis_url}   
      - redis_topics=${redis_topics}  
      - pg_url=postgresql://${db_user}:${db_pswd}@${db_host}/${db_name}     
      - app_name=${app_name}    
      - redis_task_status=${redis_task_status}  
      - start_trade_year=${start_trade_year}                
    volumes: 
      - app_code_source:/app/app
      - logs-store:/app/logs 
      - common_libs:/app/common_libs
    command: >
        bash -c "/app/start.sh"         
    ports:
      - "${app_ports}"







volumes:

  app_code_source: 
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${app_code_source} 
  logs-store: 
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${logs_dir} 

  common_libs: 
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${common_libs} 

  worker_code_source: 
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${worker_code_source} 

      

